#!/usr/bin/env bash
# Quick Test Commands Reference

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "ZETACARD TEST COMMANDS"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 RUN ALL TESTS"
echo "  npm run test:all              # Both unit + E2E (sequential)"
echo ""
echo "🧪 UNIT TESTS (Vitest)"
echo "  npm run test                  # Run once"
echo "  npm run test:watch            # Watch mode"
echo "  npm run test:ui               # UI dashboard"
echo ""
echo "🎭 E2E TESTS (Playwright)"
echo "  npm run test:e2e              # Run once (debug mode)"
echo "  npm run test:e2e:ui           # UI dashboard"
echo ""
echo "🔍 DEBUG A SPECIFIC E2E TEST"
echo "  npx playwright test -g 'test name'  # Run one test"
echo "  npx playwright test -g 'test name' --debug  # Debug with browser open"
echo ""
echo "📈 VIEW TEST RESULTS"
echo "  npx playwright show-report    # Open HTML report"
echo "  npx playwright show-trace <trace.zip>  # View trace"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "❌ WHEN TESTS FAIL"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "You will see:"
echo "  ❌ TEST FAILED"
echo "  ├─ Test name"
echo "  ├─ File path"
echo "  ├─ Error reason"
echo "  ├─ Last 5 events from __zetacard__"
echo "  └─ Last 3 console logs"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo "⚙️  CONFIGURATION"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "playwright.config.ts:"
echo "  • fullyParallel: false        (DEBUG: single worker for clear logs)"
echo "  • workers: 1                  (DEBUG: no log interleaving)"
echo "  • retries: 0                  (DEBUG: see first failure)"
echo "  • maxFailures: 1              (DEBUG: stop on first failure)"
echo ""
echo "tests/e2e/test-setup.ts:"
echo "  • Health check before each test"
echo "  • Clear failure headers with context"
echo "  • Auto-reset events"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
